apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-hub-publisher
spec:
  selector:
    matchLabels:
      app: event-hub-publisher
      tier: api-endpoint
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: event-hub-publisher
        tier: api-endpoint
        track: stable
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: firestore-key
      containers:
        - name: event-hub-publisher
          image: "gcr.io/event-hub-249001/event-hub-publisher:0.0.1-SNAPSHOT"
          imagePullPolicy: "Always"
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: GOOGLE_CLOUD_PROJECT
            value: "event-hub-249001"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          ports:
            - name: http
              containerPort: 8080
